root: true
env:
  browser: true
  es2022: true
  node: true

extends:
  - "eslint:recommended"
  - "@typescript-eslint/recommended"
  - "@typescript-eslint/recommended-requiring-type-checking"
  - "next/core-web-vitals"
  - "prettier"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"

plugins:
  - "@typescript-eslint"
  - "import"
  - "unused-imports"

rules:
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/no-explicit-any": "warn"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-non-null-assertion": "warn"
  "@typescript-eslint/prefer-const": "error"
  "@typescript-eslint/no-var-requires": "error"
  "@typescript-eslint/ban-ts-comment": "warn"
  "@typescript-eslint/no-empty-function": "warn"
  "@typescript-eslint/no-inferrable-types": "error"
  "@typescript-eslint/prefer-as-const": "error"
  
  "import/order":
    - "error"
    - groups:
        - "builtin"
        - "external"
        - "internal"
        - "parent"
        - "sibling"
        - "index"
      newlines-between: "always"
      alphabetize:
        order: "asc"
        caseInsensitive: true
  
  "import/no-duplicates": "error"
  "import/no-unused-modules": "warn"
  "import/newline-after-import": "error"
  
  # Unused imports
  "unused-imports/no-unused-imports": "error"
  "unused-imports/no-unused-vars":
    - "warn"
    - vars: "all"
      varsIgnorePattern: "^_"
      args: "after-used"
      argsIgnorePattern: "^_"
  
  "no-console": "warn"
  "no-debugger": "error"
  "no-alert": "error"
  "no-var": "error"
  "prefer-const": "error"
  "no-unused-expressions": "error"
  "no-duplicate-imports": "error"
  "no-multiple-empty-lines":
    - "error"
    - max: 1
      maxEOF: 0
  
  "complexity":
    - "warn"
    - 10
  "max-depth":
    - "warn"
    - 4
  "max-lines":
    - "warn"
    - 500
  "max-lines-per-function":
    - "warn"
    - 100
  
  "eol-last": "error"
  "comma-dangle":
    - "error"
    - "always-multiline"
  "quotes":
    - "error"
    - "double"
    - allowTemplateLiterals: true
  "semi":
    - "error"
    - "always"

overrides:
  - files:
      - "*.js"
      - "*.jsx"
    rules:
      "@typescript-eslint/no-var-requires": "off"
      "@typescript-eslint/explicit-function-return-type": "off"
  
  - files:
      - "*.test.ts"
      - "*.test.tsx"
      - "*.spec.ts"
      - "*.spec.tsx"
    rules:
      "no-console": "off"
      "@typescript-eslint/no-explicit-any": "off"
  
  - files:
      - "next.config.js"
      - "tailwind.config.ts"
      - "postcss.config.js"
      - "prettier.config.js"
    rules:
      "@typescript-eslint/no-var-requires": "off"
      "import/no-anonymous-default-export": "off"

ignorePatterns:
  - "node_modules/"
  - ".next/"
  - "out/"
  - "build/"
  - "dist/"
  - "*.min.js"
  - "public/"
  - "drizzle/"
  - "*.config.js"
  - "*.config.ts" 